-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
HAVING SCORE IN (
    SELECT MAX(SCORE_SUM)
    FROM (
        SELECT HE.EMP_NO, SUM(HG.SCORE) AS SCORE_SUM
        FROM HR_EMPLOYEES HE JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO
        GROUP BY HE.EMP_NO
    ) AS SS
);
